"""
Management command para cargar slides de presentación desde JSON.
"""
import json
from django.core.management.base import BaseCommand
from core.models import Resource, Slide


class Command(BaseCommand):
    help = 'Carga slides de presentación desde datos JSON'

    def add_arguments(self, parser):
        parser.add_argument(
            '--resource-slug',
            type=str,
            default='presentaciones-en-powerpoint-promocion-turistica',
            help='Slug del recurso al que asociar los slides'
        )

    def handle(self, *args, **options):
        resource_slug = options['resource_slug']
        
        # Datos JSON proporcionados por el usuario
        slides_data = {
            "slides": [
                {"index": 1, "text": "IA en M365. M365 Copilot y \nM365 Copilot App   \nEnero 2026"},
                {"index": 2, "text": "Izertis overview"},
                {"index": 3, "text": "Quiénes Somos  \nSomos una Consultora Tecnológica que ayuda a las organizaciones en su proceso de Metamorfosis Digital.  \nNuestra diferenciación se basa en nuestro Offering de servicios y tecnologías de vanguardia, y en nuestra Cultura moderna, ágil, innovadora\ny flexible.  \n3  \n+2.500  \nPROFESIONALES  \n+29  \nAÑOS DE HISTORIA  \n+138 M€  \nDE INGRESOS EN 2024  \nCOTIZADOS DESDE 2019"},
                {"index": 4, "text": "Quiénes Somos  \nPortugal  \nReino Unido  \nSuiza  \nEspaña  \nIndia  \nUSA  \nLATAM  \nBarcelona  \nGijón\nGranada  \nLa Coruña\nMadrid  \nMálaga\nSevilla  \nTenerife  \nValencia  \nVitoria  \nGénova  \nLondres  \nEdimburgo  \nMilton Keynes  \nNueva Delhi  \nLatam Hub  \nIndia Hub  \nEurope Hub  \n Miami  \nLisboa  \n3  \nHubs Producción\nEuropa, Latam, India  \n+25  \nPaíses con proyectos desarrollados  \nMéxico  \nMexico City  \nGuadalajara  \nColombia  \nMedellín  \nPerú  \nLima  \nGuatemala  \nGuatemala City  \nPanamá  \nPanamá City  \nEl Salvador  \nSan Salvador"},
                {"index": 5, "text": "Consultancy &\nGovernance  \nServicios de consultoría para la optimización y mejora de eficiencia operativa de las Organizaciones  \nConsultoría estratégica | Gobierno TI | Organización y Procesos | Gestión de Portfolios, Programas y Proyectos | Gestión de Servicios | Gestión del Cambio | Soluciones PPM/ESM/ITSM  \nSoftware \nEngineering  \nSoluciones para acelerar la transición hacia los negocios digitales de alto valor para el usuario  \nIADev | Agile development | DevSecOps | Mobile | Digital Platforms | ECM & BMP | Quality Assurance | Phygital  \nCX & \nBusiness Solutions  \nDesarrollo de soluciones end-to-end para aumentar la eficiencia, reducir costes y crear negocios hiper-conectados que vinculen personas, datos y procesos  \nCustomer Experience | CRM | ERP  \nCloud \n& Infrastructure  \nConsultoría centrada en infraestructuras tecnológicas basadas en Cloud  \nAdministración Delegada de Infraestructuras | Cloud Híbridas | Cloud DevOps | Modernización IT | Servicios Gestionados | Productividad | Comunicaciones  \nCybersecurity  \nSoluciones de ciberseguridad a través de un modelo de aplicación de seguridad 360  \nArquitecturas Seguras | Cyber Assessment | Auditorías | Pentesting | Red Team | Apoyo ante Incidentes | SOC  \nAI &​\nData  \nServicios y soluciones de inteligencia personalizadas para facilitar la toma de decisiones estratégicas  \nGobierno IA | Inteligencia Artificial | Data | Blockchain | PLN"},
                {"index": 6, "text": "Preparativos"},
                {"index": 7, "text": "Recursos y enlaces importantes  \nSharePoint Master: https://izertistraining.sharepoint.com/sites/master-m365-ia  \nPresentaciones  \nSoluciones  \nVínculos:"},
                {"index": 8, "text": "Acabas de comprar una casa rural en la sierra de Madrid y estás empezando a poner en marcha el negocio.  \nTu meta es tenerla lista para recibir huéspedes lo antes posible.  \nVamos a usar m365 y Copilot para ayudarnos a poner el plan en marcha:  \nSe ha creado un Equipo de Teams  \nTaller Alumnos [Fechas_Edicion]  \nCada alumno creará una Biblioteca de documentos llamada Alumno N. \nEjercicio 1. \"Casa Rural. Preparativos\""},
                {"index": 9, "text": "Introducción"},
                {"index": 10, "text": "IA, ML, Deep Learning, Generative AI\nTecnología | ¿Qué es? | Ejemplo\nInteligencia Artificial | Programas que simulan inteligencia | Siri, Alexa\nMachine Learning | IA que aprende de datos | Recomendaciones de Netflix\nDeep Learning | Redes neuronales complejas | Reconocimiento facial, voz\nGenerative AI | IA que crea contenido | ChatGPT, Gemini"},
                {"index": 11, "text": "¿Qué es un modelo de lenguaje?  \nEs un tipo de IA diseñada para predecir la siguiente palabra de un texto  \nEs entrenada con grandes cantidades de texto (Corpus) y aprende patrones de cómo usamos las palabras  \n\"Comprende\" y responde en lenguaje natural y sabe resumir, traducir, escribir, corregir texto...  \nSe sabe que funcionan y su precisión pero no \"exactamente\" como llegan al resultado: evaluamos la calidad de las respuestas."},
                {"index": 12, "text": "Mitología de los LLM  \nNO tienen memoria: No recuerdan conversaciones anteriores. 🧠❌  \nNO entienden como un humano: Predicen palabras, no comprenden. 🤖🔤  \nNO son creativos como tal: Generan combinaciones probabilísticas (temperatura, Top-K, Top-P). 🎲✨  \nNO pueden ejecutar código ni acciones reales: Solo generan contenido. ⌨️📝  \nNO saben nada que haya ocurrido tras su entrenamiento: Su conocimiento está congelado en el tiempo. 🕰️🧊  \nNO siempre dicen la verdad: Pueden \"alucinar\" y reproducir sesgos. 🦄⚠️  \nNO tienen acceso a internet. 🌐🚫  \nNO funcionan igual en todos los idiomas: mejor rendimiento en inglés (o mejor dicho, en idiomas del corpus en el que fueron entrenados). 🇬🇧👍🌍  \nNO aprenden de cada conversación (al menos en tiempo real). ⏳🙅"},
                {"index": 13, "text": "¿Qué es un copiloto o asistente de IA?  \nEs una aplicación que usa:  \nUn LLM que dirige las operaciones (razona) y crea contenido  \nHerramientas para dar más contexto y ejecutar acciones  \nUna memoria para recordar la conversación"},
                {"index": 14, "text": "M365 Copilot"},
                {"index": 15, "text": "¿Qué es Microsoft Copilot 365?  \nEs un asistente IA integrado en la plataforma de Microsoft 365: Word, Excel, Outlook, PowerPoint, Teams, OneDrive, SharePoint, Loop...  \n\"Entiende\" lo que haces y te ayuda a: redactar, resumir, buscar, analizar.  \nFunciona con tus documentos, correos, reuniones. Es como ChatGPT pero con acceso a tu información.   \nNo se debe confundir con Microsoft Copilot Chat (licencia de M365 estándar)  \nRedactar emails, informes, presentaciones  \nAnalizar hojas de cálculo y sugerir gráficos  \nResumir reuniones, chats   \n y documentos  \nBuscar información en    \n tus archivos  \nDirección: resumen de actas, planificación.  \nRRHH: descripción de puestos, comunicaciones internas.  \nMarketing: borradores de campaña, informes de audiencia.  \nComercial: respuestas a clientes, propuestas."},
                {"index": 16, "text": "¿Cómo funciona Copilot para Microsoft 365?  \nhttps://learn.microsoft.com/es-es/microsoftsearch/semantic-index-for-copilot#data-flows"},
                {"index": 17, "text": "Seguridad y privacidad en \nCopilot 365\n- Microsoft asegura que ni los prompts, ni las respuestas, ni los datos obtenidos a través de Microsoft Graph para dar contexto al LLM se usan para entrenar los modelos.\n- El sistema se implanta sobre el tenant perteneciente a tu organización, por lo que tus datos no se cruzan con el de otras organizaciones.\n- Los mismos permisos que aplican en la plataforma de Microsoft 365 aplican en el uso de Copilot: Solo lo que puedo ver como usuario en Microsoft 365 podrá ser usado por Microsoft Graph para dar contexto al modelo en la generación de las respuestas.\n- Microsoft Copilot por tanto combinará la información relevante para la cuestión que esté disponible en Microsoft Graph y que el usuario tiene acceso junto con la información de su base de conocimiento como LLM para generar las respuestas.\nhttps://learn.microsoft.com/es-es/graph/overview"},
                {"index": 18, "text": "Manos a la obra con Copilot para Microsoft 365"},
                {"index": 19, "text": "¿Dónde empezar ?  \nRecursos oficiales de aprendizaje: https://support.microsoft.com/en-us/microsoft-365-copilot  \nAsistente  \nGuías  \nCursos  \nVideos"},
                {"index": 20, "text": "¿Qué es Chat en Microsoft M365 Copilot?  \nEs un espacio centralizado para interactuar con herramientas y documentos.  \nPermite conversaciones multi-turno con acceso a información y archivos.  \nFacilita la colaboración en equipo mediante integración con Outlook y Teams.  \nOfrece funciones avanzadas como búsqueda, edición y personalización de respuestas."},
                {"index": 21, "text": "Microsoft M365 Copilot app. Chat  \nhttps://m365.cloud.microsoft/chat  \nSolo información pública\nSimilar a https://copilot.microsoft.com/  \nTiene acceso a información interna  \nEjemplos de prompts  \nAgregar ficheros    \npara trabajar \"hablar\" con ellos  \nElegir modelo  \nPersonalizar Copilot  \nActivar búsquedas Web para enriquecer respuestas  \nNueva conversación  \nInvocar un agente \"@\"  \nHablando con mis ficheros, bandeja de entrada, reuniones, calendario… \"/\"   \nEditar en Pages (similar a lienzo de ChatGPT)"},
                {"index": 22, "text": "M365 Copilot  \nApp Demo  \nConfiguración  \nChat Web / Trabajo  \nDesigner (Imágenes)  \nBuscador  \nAgentes  \nPages  \nBiblioteca  \nCuadernos"},
                {"index": 23, "text": "¿Qué es un prompt?  \nUn prompt es la instrucción o mensaje que le das a la IA.  \nGeneralmente a través de un asistente  \nEl prompt te permite enseñar al modelo qué y cómo debe responder en cada situación, definiendo tono, formato, enfoque, comportamiento...  \nPrompt engineering = saber formularlo bien. Cuanto más preciso sea, mejores respuestas obtendrás.  \nElementos de un  prompt  \nDatos de entrada. (User Role).  \nInstrucción (System Role)   \nContexto (Grounding)  \nFormato de Salida (Texto o Json)"},
                {"index": 24, "text": "Usa delimitadores o formatos como Markdown para separar secciones (===, \"\"\", </>).  \nPide formatos estructurados (listas, tablas, JSON, etc.) si vas a reutilizar la información.  \nVerifica condiciones previas: pídele que analice si el texto está listo para ser usado o necesita limpieza.  \nIncluye ejemplos (In Context Learning).  \nGuía paso a paso: divide el problema en subtareas o indica cómo debe abordar la solución.  \nUsa placeholders ([Nombre], {Fecha}, ____) para facilitar recogida de información o personalización.  \nEvita ambigüedades: sé explícito en lo que quieres (formato, tono, extensión, rol, etc.).  \nAlgunas técnicas de prompt"},
                {"index": 25, "text": "Patrón Persona: Define el rol o identidad que debe adoptar el modelo para guiar el estilo y enfoque de sus respuestas  \nEres un abogado experto en derecho digital con 20 años de experiencia.   \nInstrucciones metacognitivas: pídele que revise su respuesta antes de entregarla   \n¿Hay alguna parte de tu respuesta que pueda no ser cierta?. Revísala  \nPatrón Chain-of-Thoughts: Pide al modelo que razone paso a paso antes de llegar a una conclusión  \nCuántos patas tienen 3 perros? Piensa paso a paso antes de responder.\"  \nPatrón Multiturno: técnica en la que el modelo interactúa contigo a través de varias rondas de conversación o turnos, en lugar de recibir toda la información en un único prompt.   \nPatrón Meta-prompt: es un prompt que no da instrucciones directas sobre la tarea final, sino que define cómo debe generarse el prompt ideal para esa tarea\nAlgunas técnicas de prompt"},
                {"index": 26, "text": "¿Qué es Pages en Microsoft M365 Copilot?  \nPages es una herramienta de borrador para guardar resultados de conversaciones con Copilot   \n Funciona como un lienzo interactivo similar a ChatGPT, pero con edición manual.   \n Permite colaboración en tiempo real y compartir páginas con tu equipo fácilmente.   \n Las páginas se guardan indefinidamente y el contenido es editable manualmente."},
                {"index": 27, "text": "Microsoft M365 Copilot app. Pages  \nPuedes editar el resultado obtenido desde el Chat de Copilot en modo borrador...  \nDesde el chat  \nDirectamente desde el lienzo  \nCrear un Word desde la Page  \nAgregar Page a un cuaderno"},
                {"index": 28, "text": "¿Qué son los Agentes en Microsoft M365 Copilot?  \nLos agentes son asistentes inteligentes que automatizan tareas específicas.  \nInteractúan con usuarios para ofrecer respuestas y soluciones contextuales.  \nSe integran con diversas aplicaciones dentro del ecosistema M365.  \nFacilitan la productividad mediante procesos personalizados y adaptativos."},
                {"index": 29, "text": "Microsoft M365 Copilot app. Agentes  \nCrear agente personalizado  \nBuscar agentes preconstruidos"},
                {"index": 30, "text": "Ejercicio 2. Guía de usuario de la Casa Rural   \nPediremos a Copilot que nos ayude a crear una guía de usuario para nuestra Casa Rural.   \nUsa el Agente llamado Prompt Coach para crear un prompt que genere una primera guía de usuario: (Metaprompt y  Multiturno)  \nEjecuta tus instrucciones en un chat nuevo de Copilot.  \nUna vez obtenido lo añadiremos a Pages para trabajar sobre él.  \nGuárdalo en un documento Word en el sitio SharePoint de la Casa Rural en una carpeta llamada MANUALES dentro de la biblioteca del Alumno N."},
                {"index": 31, "text": "De palabras a tokens  \nLos modelos NO leen palabras, leen tokens (fragmentos de texto).  \nLa tokenización divide el texto en unidades mínimas que el modelo pueda entender.  \nCada token se convierte en un número que luego se usa para cálculos matemáticos: embeddings  \nEl número de tokens afecta al coste y al límite de contexto de los modelos."},
                {"index": 32, "text": "Búsqueda semántica  \nBusca por significado, no por palabras exactas.  \nEntiende el contexto, sinónimos e intención de la consulta.  \nMejora el acceso a documentos, bases de datos y respuestas inteligentes."},
                {"index": 33, "text": "Retrieval Augmented Generation (RAG)  \nTécnica que sirve para mejorar las respuestas de nuestros LLMs aumentando el contexto.  \nUsuario hace una pregunta.  \nLa aplicación o asistente hace la misma pregunta a una base de datos especialista en búsquedas semánticas donde previamente hemos guardado nuestros documentos.  \nLa aplicación usa la información recuperada para ampliar el contexto de la búsqueda inicial y enviarla al LLM.  \nIA genera una respuesta usando lo que sabe + lo que se le proporciona en la búsqueda."},
                {"index": 34, "text": "¿Qué son los Cuadernos en Microsoft M365 Copilot?  \nLos Cuadernos son espacios digitales para organizar información y notas.  \nPermiten integrar contenido generado por Copilot con anotaciones manuales.  \nFacilitan la colaboración en equipo con actualizaciones en tiempo real.  \nSon accesibles desde diversas aplicaciones dentro del ecosistema Microsoft 365."},
                {"index": 35, "text": "Microsoft M365 Copilot app. Cuadernos  \nCrear cuaderno  \nMis cuadernos"},
                {"index": 36, "text": "Crearemos un Cuaderno: Regulación Casas Rurales que nos ayude, como propietarios de la Casa Rural, a comprender e interpretar de manera viva, los documentos de la Regulación y Normativa de Casas Rurales.  \nCrea una nueva carpeta en la biblioteca de documentos del alumno llamada NORMATIVA y copia en ella los documentos de que regulan las Casas Rurales (ejemplos en carpeta de soluciones).  \nCrea un cuaderno usando los ficheros en esa nueva carpeta.  \nUsa el Agente de Prompts para crear instrucciones personalizadas para el cuaderno.  \nCrea un audio sobre modalidades de tipo de alojamiento y sus características específicas\nEjercicio 3. Cuaderno para aprender la Regulación de Casas Rurales"},
                {"index": 37, "text": "¿Qué es Microsoft M365 Copilot Designer (Crear)?  \nHerramienta de diseño gráfico integrada en entorno empresarial para diseñar presentaciones y contenido visual.  \nUtiliza IA para sugerir diseños, estilos y organización de diapositivas.  \nPermite personalización rápida y ajustes dinámicos en tiempo real.  \nFacilita la creación de materiales profesionales y atractivos fácilmente."},
                {"index": 38, "text": "Microsoft M365 Copilot app. Designer"},
                {"index": 39, "text": "Ejercicio 4. Casa Rural y Logotipo.  \nUsando Designer:  \nCrea una foto de una Casa Rural \"inventada\".   \nBusca una foto en internet de alguna casa rural como base para tu foto (ingeniería inversa). Guárdalas en tu biblioteca de documentos.  \nDiseña un logo para nuestra casa rural.   \nHaz Meta-prompting con algún generador de prompts: Prompt Coach, GPT de ChatGPT  \nGuarda ambas imágenes en tu biblioteca de documentos."},
                {"index": 40, "text": "Ejercicio 5. Agente Asesor de Regulación  \nUna alternativa al cuaderno del Ejercicio 3 es crear un Agente para resolver las dudas de normativa y regulación.  \nDiseña un logo para el agente en el designer. Usa un Agente de Prompting  \nUsa un Agente de Prompting para crear las instrucciones de nuestro Agente Asesor de regulación  \nCrea el Agente desde una carpeta (NORMATIVA) en la Biblioteca del alumno, usando las instrucciones, el logo y los documentos de normativa que se encuentran en las soluciones."},
                {"index": 41, "text": "Ejercicios resueltos"},
                {"index": 42, "text": "Ejercicio 1. Nuevo Biblioteca de alumno en SharePoint del alumno  \nEn SharePoint pulsa en Nuevo elemento y después Biblioteca de documentos: Biblioteca en blanco"},
                {"index": 43, "text": "Ejercicio 2. Crear un prompt con Prompt Coach  \nDesde https://m365.cloud.microsoft/chat/ selecciona Todos los agentes, busca el agente Prompt Coach y Agrégalo  \nSelecciona Prompt Coach y conversa con el agente hasta obtener un un prompt adecuado:"},
                {"index": 44, "text": "Ejercicio 2. Crear la guía en Word.  \nCreate a comprehensive Guest Guide for the rural house called **\"Casa Rural El Olivo\"**. The guide should have a **warm and welcoming tone**, be **well-structured with clear sections**, and include realistic and useful information for guests. Organize the content into the following sections:  \n1. **Welcome & Introduction**    \n   - A friendly welcome message and a brief description of the house.  \n2. **Available Services**    \n   - Explain how to use all amenities: swimming pool, Wi-Fi, heating system, TV and streaming services, fully equipped kitchen, fireplace, parking, and any other relevant features.  \n3. **House Rules**    \n   - Basic rules for safety, maintenance, and respectful use of the property.  \n4. **Practical Tips**    \n   - Helpful advice for enjoying the stay (e.g., pool usage times, fireplace safety, energy-saving tips).  \n5. **Local Recommendations**    \n   - Suggest nearby shops, traditional bars and restaurants, hiking trails, excursions, and cultural activities in the area.  \n6. **Emergency & Contact Information**    \n   - Provide useful phone numbers and instructions to contact the property owner.  \n**Additional Requirement:**    \nGenerate the document **first in Spanish** and then **in English**, keeping the same structure and tone in both versions.  \n**Expected Output:**    \nA well-organized document with headings and subheadings, written in a clear and friendly style, including practical tips and local recommendations"},
                {"index": 45, "text": "Ejercicio 3. Crear un cuaderno. Añade referencias:  \nCuadernos > Nuevo bloc de notas > Agregar referencias >  Adjuntar archivos en la nube    \nCrear cuaderno con las referencias seleccionadas:"},
                {"index": 46, "text": "Ejercicio 3. Crear un cuaderno. Añade instrucciones:  \nUsa el Prompt Coach y trabaja con él hasta obtener unas instrucciones adecuadas:  \nAñade el prompt obtenido como instrucciones del cuaderno:  \nQuiero crear instrucciones personalizadas para un cuaderno (bloc de notas) de m365 que contiene documentos de referencia.   \nEl cuaderno sirve para aprender y resolver dudas relacionadas con la normativa legal de las casas rurales en España y en concreto en la Comunidad de Madrid.  \nSiempre se debe, para responder al usuario, usar la información encontrada en los documentos de referencia, nunca inventar o usar el conocimiento del modelo.  \n- Responde únicamente utilizando la información de referencia.   \n- No uses conocimiento externo ni inventes datos.   \n- Si la respuesta no está en los documentos de referencia, indica claramente: 'No hay información disponible en el cuaderno para responder a la consulta'.  \n- El usuario es propietario o personal encargado de la gestión de casas rurales, por lo que las explicaciones deben ser claras, sencillas y prácticas.  \n- Formato de respuesta:  \n  - Explicación breve y directa.  \n  - Incluye la referencia al documento o sección donde se encuentra la información.  \n  - Solo añade detalles adicionales si el usuario lo solicita expresamente."},
                {"index": 47, "text": "Ejercicio 3. Crear un cuaderno. Introducción de audio  \nObtener introducción de audio > Personaliza el audio:"},
                {"index": 48, "text": "Ejercicio 4. Crear foto de la Casa Rural  \nBusca una foto en internet y agrégala. Diseña un prompt para crear una imagen similar. Selecciona un estilo \"Photorealistic\" y Orientación ancho (ojo porque el texto es confuso)  \nAñade Texto a la imagen con su nombre, haz tus Ajustes y mejoras:"},
                {"index": 49, "text": "Ejercicio 4.1 Crear foto de la Casa Rural  \nOriginal  \nResultado"},
                {"index": 50, "text": "Ejercicio 4.2 Crear logotipo de la Casa Rural  \nDiseña un prompt usando Prompt Coach (u otro asistente) para crear un logo:  \nSelecciona la imagen del ejercicio anterior (Mis imágenes) y edítala, elimina el texto, aplica filtros, recorta...  \nLogotipo basado en la imagen proporcionada para una casa rural.  Colores en tonos tierra (marrones, verdes apagados, beige). Fondo blanco, formato cuadrado, estilo vectorial minimalista, sin texto, ideal para impresión y uso digital."},
                {"index": 51, "text": "Ejercicio 4.2 Crear logotipo de la Casa Rural"},
                {"index": 52, "text": "Ejercicio 5. Crear un Agente (de Biblioteca). El logotipo:  \nUsando Prompt Coach crea un prompt para usar en Designer:  \nEn Designer, crea un logo cuadrado para el Agente usando el prompt obtenido y descárgalo en formato .png:"},
                {"index": 53, "text": "Ejercicio 5. Crear un Agente (de SharePoint).   \nUsa Prompt Coach para crear las instrucciones del Agente:  \nEn SharePoint en la Biblioteca de documentos de Alumno > NORMATIVA > Acciones de IA > Crear un Agente:  \nEres un asistente especializado en normativa y regulación de Casas Rurales. Tu comportamiento debe seguir estas reglas:  \n1. Responde únicamente utilizando la información contenida en las fuentes de conocimiento proporcionadas.  \n2. No inventes información ni uses fuentes externas.  \n3. Si no encuentras información en las fuentes, indica claramente: \"No hay información disponible en las fuentes\".  \n4. Mantén las respuestas breves y directas, salvo que el usuario solicite más detalle.  \n5. Incluye siempre la referencia a la normativa o documento utilizado (nombre del documento, artículo, página).  \n6. No proporciones consejos prácticos ni opiniones. Limítate a normativa y regulación."},
                {"index": 54, "text": "Ejercicio 5. Crear un Agente (de SharePoint).   \nDesde SharePoint edita el agente:  \nFichero que describe el agente  \nLogo  \nPropósito"},
                {"index": 55, "text": "Ejercicio 5. Crear un Agente (de SharePoint).  \nOrígenes de conocimiento (RAG)  \nPersonalizar comportamiento.  \nMensaje inicial  \nEjemplos de prompt  \nInstrucciones del agente"},
                {"index": 56, "text": ""}
            ]
        }
        
        self.stdout.write(self.style.WARNING(f'Buscando recurso con slug: {resource_slug}...'))
        
        try:
            resource = Resource.objects.get(slug=resource_slug)
        except Resource.DoesNotExist:
            self.stdout.write(self.style.ERROR(f'✗ No se encontró el recurso con slug: {resource_slug}'))
            self.stdout.write(self.style.WARNING('Recursos disponibles:'))
            for r in Resource.objects.all():
                self.stdout.write(f'  - {r.slug}')
            return
        
        self.stdout.write(self.style.SUCCESS(f'✓ Recurso encontrado: {resource.title}'))
        
        # Eliminar slides existentes para este recurso
        deleted_count = Slide.objects.filter(resource=resource).count()
        if deleted_count > 0:
            Slide.objects.filter(resource=resource).delete()
            self.stdout.write(self.style.WARNING(f'✓ Eliminados {deleted_count} slides existentes'))
        
        # Crear los slides
        created_count = 0
        for slide_data in slides_data['slides']:
            # Extraer título del texto (primera línea no vacía)
            text = slide_data['text'].strip()
            lines = [line.strip() for line in text.split('\n') if line.strip()]
            title = lines[0] if lines else f"Slide {slide_data['index']}"
            
            # Si el título es muy largo, truncarlo
            if len(title) > 200:
                title = title[:197] + "..."
            
            Slide.objects.create(
                resource=resource,
                slide_number=slide_data['index'],
                title=title,
                content=text,
                order=slide_data['index']
            )
            created_count += 1
        
        self.stdout.write(self.style.SUCCESS(f'\n✓ {created_count} slides creados correctamente para "{resource.title}"'))
