# Generated by Django 4.2.8 on 2026-01-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="folder",
                        help_text="Nombre del icono Bootstrap",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="secciones/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True)),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("link", "Enlace Externo"),
                            ("document", "Documento"),
                            ("video", "Video"),
                            ("image", "Imagen"),
                            ("exercise", "Ejercicio"),
                            ("tool", "Herramienta"),
                        ],
                        default="link",
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="URL del recurso externo", null=True
                    ),
                ),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="Ej: 30 min, 1 hora", max_length=50
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("intermedio", "Intermedio"),
                            ("avanzado", "Avanzado"),
                        ],
                        default="basico",
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="core.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
                "ordering": ["section", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("normativa", "Normativa"),
                            ("guia", "Guía"),
                            ("manual", "Manual"),
                            ("plantilla", "Plantilla"),
                            ("referencia", "Referencia"),
                        ],
                        default="referencia",
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="documentos/normativos/")),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["order", "title"],
            },
        ),
    ]
