# Generated by Django 4.2.8 on 2026-01-26 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slide_number",
                    models.IntegerField(help_text="Número de la diapositiva"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Título extraído de la diapositiva",
                        max_length=300,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Contenido textual de la diapositiva"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Captura de la diapositiva",
                        null=True,
                        upload_to="slides/",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notas del presentador"),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="core.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diapositiva",
                "verbose_name_plural": "Diapositivas",
                "ordering": ["resource", "slide_number"],
                "unique_together": {("resource", "slide_number")},
            },
        ),
    ]
